name: Tests

on:
  push:
  pull_request:

jobs:
  fast:
    name: Fast checks
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        fzf: [false]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup packages (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh git $([ "${{ matrix.fzf }}" = "true" ] && echo fzf || true)

      - name: Run fast tests
        shell: bash
        run: |
          FAST_ONLY=1 bash tests/run.sh

  full:
    name: Full matrix
    needs: fast
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        fzf: [true, false]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup packages (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh git $([ "${{ matrix.fzf }}" = "true" ] && echo fzf || true)

      - name: Setup packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install zsh git $([ "${{ matrix.fzf }}" = "true" ] && echo fzf || true)

      - name: Run full tests
        shell: bash
        run: |
          echo "Tool versions:" && zsh --version && git --version && awk --version || true
          echo "PATH=$PATH" && which -a zsh || true && which -a awk || true
          bash tests/run.sh


