name: Test Suite

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
      fail-fast: false
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Git
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"
      
      - name: Setup Zsh (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
      
      - name: Verify Zsh installation
        run: |
          zsh --version
          which zsh
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/*
          chmod +x tests/*.sh tests/*.zsh tests/run_all.zsh
          chmod +x tests/lib/*.sh tests/lib/*.zsh
          chmod +x tests/regression/*.zsh
      
      - name: Run Lint
        run: make lint
        continue-on-error: true
      
      - name: Run Legacy Tests
        run: bash tests/run.sh
      
      - name: Run New Test Framework - All
        run: zsh tests/run_all.zsh all
      
      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.os }}
          path: |
            .coverage/
            tests/**/*.log
          retention-days: 7

  test-fast:
    name: Quick Tests
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Git
        run: |
          git config --global user.name "Test User"
          git config --global user.email "test@example.com"
      
      - name: Setup Zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
      
      - name: Make scripts executable
        run: |
          chmod +x scripts/*
          chmod +x tests/*.sh tests/*.zsh tests/run_all.zsh
      
      - name: Run Fast Tests
        run: make test-fast
        env:
          FAST_ONLY: 1

  lint:
    name: Syntax Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Setup Zsh
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh
      
      - name: Run Lint
        run: make lint
