name: Tests

on:
  push:
  pull_request:

jobs:
  build:
    name: CI matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        fzf: [true, false]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup packages (Ubuntu)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y zsh git $([ "${{ matrix.fzf }}" = "true" ] && echo fzf || true)

      - name: Setup packages (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install zsh git $([ "${{ matrix.fzf }}" = "true" ] && echo fzf || true)

      - name: Run tests
        shell: bash
        env:
          PATH: ${{ env.PATH }}
        run: |
          bash tests/run.sh


